version: '3.9'
services:
  wp_redis:
    container_name: wp_redis
    image: 'redis:7'
    networks:
      - wp
  wp_memcached:
    container_name: wp_memcached
    image: 'bitnami/memcached:latest'
    environment:
      MEMCACHED_CACHE_SIZE: 64
    networks:
      - wp
  wp_db:
    container_name: wp_db
    image: 'mariadb:latest'
    restart: unless-stopped
    networks:
      - wp
    volumes:
      - 'wp-db-volume:/var/lib/mysql:rw'
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
    ports:
      - '3308:3306'
  wp_cron:
    container_name: wp_cron
    build:
      context: ./docker
      dockerfile: cron-Dockerfile
    command: supercronic crontab
    networks:
      - wp
  wp_php:
    container_name: wp_php
    build:
      context: ./docker
      dockerfile: phpfpm-Dockerfile
    image: 'wp_php:8.2'
    volumes:
      - './site:/srv/www'
      - './docker/conf/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf'
      - './docker/conf/php-fpm/php.ini:/usr/local/etc/php/php.ini'
    networks:
      - wp
  wp_nginx:
    container_name: wp_nginx
    image: 'nginx:stable-alpine'
    ports:
      - '8081:80'
    volumes:
      - './site:/srv/www'
      - './docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    networks:
      wp:
        aliases:
          - wordpress.local
    depends_on:
      - wp_php
      - wp_db
      - wp_redis
      - wp_memcached
      - wp_mailhog
  wp_mailhog:
    container_name: wp_mailhog
    image: mailhog/mailhog
    networks:
      - wp
networks:
  wp:
    driver: bridge
volumes:
  wp-db-volume: {  }
